### PR TITLE
add OCB2 crypto for use in UDP implementation

### PR DESCRIPTION
**Pull request by anewusername**
Based on the last comment in #66, I took a look at Mumble's AES-OCB2 implementation and put together a quick python implementation based on pycryptodome's AES and Mumble's test suite.

It probably still needs some edits for style etc., but it passes the tests so I figured I'd ask for input and gauge interest.

### CODE REVIEW

**Comment by azlux** [comment]
The port you have done is impressive.
I don't have the skill to test encryption strength and is good implementation.

You have push the lib as part of pymumble. I think it's can be good have have it as separated lib later.
I will merge this code in few days since it's not used by the code, this will help dev to implement UDP part.

**Comment by anewusername** [comment]
I cleaned things up a bit more and added a some function headers and type hints.

I can move it out of the pymumble directory (or into a sub-package) if you'd prefer to have it elsewhere, or I could even create a separate package on PyPI if you'd prefer to keep the code in a separate repo.

**Comment by azlux** [comment]
Hi,
I think we have 3 possibilities.
1. We keep in inside this project (nobody else will be able to use it easily)
2. I make a project where you have collaborator, I've CI and pypi account already set.
3. You make your own project, I use it with through pypi.

**Comment by anewusername** [comment]
I'm happy with any of the three -- I likely won't maintain this code long-term so (1-2) seem slightly better, but (3) isn't much extra effort on my part either.

**Comment by azlux** [comment]
Let's merge this code for now. Mumble dev are thinking about changing the crypto in a next step because OCB2 is quite specific.
Depending of their progress I will transform this lib into a separate project or not.

**Comment by TerryGeng** [comment]
Thanks for the great work! I will implement UDP support based on your crypto module in a few weeks.

And I think I still need to do some benchmarking to see the CPU cost and memory usage. If that looks good, then I think we got a reason to celebrate!

**Comment by azlux** [comment]
hi @anewusername , I'm trying to implement the UDP part on pymumble.
See https://github.com/azlux/pymumble/tree/test_udp -test_udp branch).
I have one question. 
When I need to set an ocb key. I need the raw_key, a encrypt_iv and a decrypt_iv.
What are `decrypt_iv` and `encrypt_iv`  ? Any documentation about that ? 

I've supposed I need to use the server and client nonce https://mumble-protocol.readthedocs.io/en/latest/establishing_connection.html#crypto-setup. But I'm still not able to have a UDP ping working >.<

**Comment by TerryGeng** [comment]
These values are defined in `CryptSetup` packets. See L388 of `mumble.py`.

The server will send a `CryptSetup` packet once the UDP connection is ready and what you need is to add a callback when receiving this packet, below L388.

I remembered in our discussion in the IRC, I briefly explained my previous implementation of UDP transmission, but sadly that branch wasn't pushed to github and was accidentally trashed by me...

I will spend some time in the coming days to see how to reimplement it with this new OCB2 implementation.

But meanwhile, I'm working with mumble team on a new encryption scheme that enables other encryption methods like AES-128-GCM and ChaCha, thus whether we need to implement OCB2 becomes a question.

**Pull request merged**
